### ISSUE TITLE
Question about image of 3DMatch dataset

### ISSUE THREAD

**Issue by Shi-Qi-Li** [Jiang0903/IGReg#1]
Hi @Jiang0903 ,
Thanks for your work and sharing the code. I have a question regarding the images in the 3DMatch dataset. Since the original 3DMatch dataset is an RGB-D dataset and the point clouds are derived from the RGB-D sequences, I am curious how to determine which image is associated with a particular point cloud. Typically, there are about 50 images associated with one point cloud. Could you provide guidance about this process? Any help is appreciated.

**Comment by Jiang0903** [comment]
Hi @Shi-Qi-Li ,
In the data provided by [Predator](https://overlappredator.github.io/), we can find files in the format of `cloud_bin_x.info.txt`. 

In the first line of this kind of file, we can find information about `scene`, `sequence`, `first id` and `last id`. 

Here, the `first id` and `last id` refer to the initial id and the final id of the continuous 50 RGB-D images used to reconstruct `cloud_bin_x.pth`.

**Comment by Shi-Qi-Li** [comment]
> Hi @Shi-Qi-Li , In the data provided by [Predator](https://overlappredator.github.io/), we can find files in the format of `cloud_bin_x.info.txt`.
> 
> In the first line of this kind of file, we can find information about `scene`, `sequence`, `first id` and `last id`.
> 
> Here, the `first id` and `last id` refer to the initial id and the final id of the continuous 50 RGB-D images used to reconstruct `cloud_bin_x.pth`.

Hi @Jiang0903 ,
Thanks for your reply. Maybe I did not clearly express my question. For `cloud_bin_x.pth`, 50 images from `first_id` to `last_id` are used to create it, my question is which specific image is used to execute feature extraction and Intra-Image-Geometry Fusion? Because for a single point cloud, you have 50 candidates images but it seems only one image is picked.

**Comment by Jiang0903** [comment]
Hi @Shi-Qi-Li ,

I am sorry for misunderstanding you previous question.

In our work, we select the first image in IIG module. In other words, the image id is `first_id`.

Besides, in our dataset, `cloud_bin_x_0.png` corresponds to the image of `first_id` and `cloud_bin_x_1.png` corresponds to the image of `last_id`.

**Comment by Shi-Qi-Li** [comment]
> Hi @Shi-Qi-Li ,
> 
> I am sorry for misunderstanding you previous question.
> 
> In our work, we select the first image in IIG module. In other words, the image id is `first_id`.
> 
> Besides, in our dataset, `cloud_bin_x_0.png` corresponds to the image of `first_id` and `cloud_bin_x_1.png` corresponds to the image of `last_id`.

Thank you very much for your kindly reply, that solved my question.
